bandNames = ["Petty Education",
"Congress Freckle",
"Franchise",
"Breathe Faun",
"Manly Pandas",
"Monsoon",
"Some Herd Trouble",
"Seagull Sensor Drive",
"Narcissus",
"Binaural Dropout",
"Chuck Tore",
"Bran",
"Minimax Bay Ewe",
"Minimax Skunks",
"Squirrel",
"Rosemary Starve",
"Pariah Amino",
"Loudspeaker",
"Urban Criterion Theirs",
"Antennas Ricochet",
"Sprout Shrew",
"This Commanders",
"Destructor",
"Lands",
"Bow Alibis Management 8900 Catcher",
"Shrews Ban",
"An Warrant",
"Blossom",
"Ladies Reclamation Habitual",
"Cassette",
"Cocky Magpie",
"Fiend Minus Quixotic",
"Attic Genealogy",
"Biochemical Startup",
"Chieftains Glossary",
"Millipede Societal",
"Farmer Minstrel",
"56265 Sculptors Beside",
"Peasant Engineered",
"Naval",
"Scoundrel",
"Painter Pigment",
"Identification Commissioning",
"Grip",
"Track Botanical",
"Vernacular Fasteners",
"Abundantly Arsenic",
"Brashly Heaps",
"Business Cigar",
"Goodby Celebration",
"Investment",
"Twelves",
"Bravo Overheard Enlightenment",
"Automata Politics",
"Idiotic",
"Botanical Dime",
"Cloud",
"Botanical Bodybuilding"]