genres = {  "Alternative" : [ "Alternative Rock",
                            "College Rock",
                            "Experimental Rock",
                            "Goth / Gothic Rock",
                            "Grunge",
                            "Hardcore Punk",
                            "Hard Rock",
                            "Indie Rock",
                            "New Wave",
                            "Progressive Rock",
                            "Punk",
                            "Shoegaze (with thx to Jackie Herrera)",
                            "Steampunk (with thx to Christopher Schaeffer) " ],

            "Blues" : [ "Acoustic Blues",   
                      "Chicago Blues",    
                      "Classic Blues",    
                      "Contemporary Blues",   
                      "Country Blues",    
                      "Delta Blues",  
                      "Electric Blues"],

            "Classical" : [   "Avant-Garde",
                            "Baroque",
                            "Chamber Music",
                            "Chant",
                            "Choral",
                            "Classical Crossover",
                            "Early Music",
                            "High Classical",
                            "Impressionist",
                            "Medieval",
                            "Minimalism",
                            "Modern Composition",
                            "Opera",
                            "Orchestral",
                            "Renaissance",
                            "Romantic",
                            "Wedding Music"],       
    
            "Rock" : [    "Acid Rock (with thanks to Alex Antonio)",
                        "Adult Alternative",
                        "American Trad Rock",
                        "Arena Rock",
                        "Blues-Rock",
                        "British Invasion",
                        "Death Metal / Black Metal",
                        "Glam Rock",
                        "Gothic Metal",
                        "Hair Metal",
                        "Hard Rock",
                        "Metal",
                        "Noise Rock",
                        "Jam Bands",
                        "Prog-Rock/Art Rock",
                        "Psychedelic",
                        "Rock & Roll",
                        "Rockabilly",
                        "Roots Rock",
                        "Singer/Songwriter",
                        "Southern Rock",
                        "Surf",
                        "Tex-Mex" ]

    }
