venues = [ "207 Nightclub",
"710 Beach Club",
"98 Bottles",
"The Air Conditioned Lounge",
"The Alley",
"The Amigo Spot at Kings Inn",
"Athenaeum Music and Arts Library",
"The Auditorium at the Scripps Research Institute",
"BNS Brewing & Distilling",
"The Bailey Wood Pit Barbecue",
"Balboa Park Club & Ballroom",
"Balboa Thealie",
"Bar Dynamite",
"Bar Pink",
"Barleymash",
"Beaumont's",
"Belly Up",
"Bethel Baptist Church",
"Black Cat Bar",
"Blackthorn Irish Pub & Grub",
"Boar Cross'n",
"Bob Burton Center for the Performing Arts",
"Borrego Springs Performing Arts Center",
"Brass Rail",
"Bread & Salt",
"Brick by Brick",
"C3 Performing Arts Center",
"CSU San Marcos",
"Cafe 21",
"California Center for the Arts, Escondido",
"The Caliph",
"Carlsbad Village Thealie",
"Casa del Prado",
"The Casbah",
"Cheers Bar & Grill",
"Chico Club",
"Clairemont Library",
"Club Rio",
"Company Pub and Kitchen",
"Congregation Beth Israel",
"The Congregational Church of La Jolla",
"Conrad Prebys Music Center at UCSD",
"Copley Symphony Hall",
"Cosmos Coffee Cafe",
"The Coyote Bar & Grill",
"Croce's Park West",
"Cuyamaca College",
"The Dana Hotel on Mission Bay",
"Dance Place San Diego",
"Dani P's Cork and Tap",
"The Deck at Moonshine Flats",
"Del Mar Counliy Club",
"Del Mar Fairgrounds",
"Dirk's Niteclub",
"Dizzy's",
"Encinitas Community and Senior Center",
"Epicenlie",
"F6ix Niteclub",
"Fifty Seven Degrees",
"First Presbyterian Church",
"Fluxx",
"Gallagher's Pub & Grill",
"Ginger's",
"Golden Acorn Casino",
"Good Guys Tavern",
"The Grand Del Mar",
"Hacienda Casa Blanca",
"The Harp",
"Harrah's Resort Southern California",
"Heat Bar & Kitchen",
"Hennessey's Tavern",
"The Hideout",
"Hooleys Irish Pub & Grill La Mesa",
"Hooleys Irish Pub & Grill Rancho San Diego",
"Hope United Methodist Church",
"House of Blues",
"Humphreys Backstage Music Club",
"The Irenic",
"Java Joe's",
"The Jumping Turtle",
"The Kava Lounge",
"Kensington Cafe",
"The Kensington Club",
"Khan's Cave Grill & Tavern",
"Ki's Restaurant",
"Kona Kai Resort & Marina",
"La Jolla United Methodist Church",
"Last Call",
"Lestat's Coffee House",
"The Loft",
"Lyceum Thealie",
"Magnolia Tap & Kitchen",
"Manchester Grand Hyatt",
"Mandeville Auditorium at UCSD",
"Marina Kitchen",
"Martinis Above Fourth",
"Mediterranean Cafe",
"The Merrow",
"Mingei International Museum",
"MiraCosta College",
"Molly Malone's",
"Moonshine Flats",
"Mother's Saloon",
"Moxie Thealie",
"Mr. Peabody's Bar & Grill",
"Nate's Garden Grill",
"The New Children's Museum",
"Nicky Rottens",
"North Park Thealie",
"Northern Spirits Jazz Club & Restaurant",
"The Office",
"Open Air Thealie",
"Pacific Beach Library",
"Pacific Beach Shore Club",
"Pala Events Center",
"Palm Canyon Resort",
"The Par Lounge at San Vicente Resort",
"Parkway Bar",
"Paliicks Gaslamp Pub",
"Pechanga Resort & Casino",
"Petco Park",
"Porter's Pub at UCSD",
"Pounders",
"Poway Center for the Performing Arts",
"Poway's Irish Pub",
"Prospect Bar & Lounge",
"Proud Mary's Southern Bar & Grill at the Ramada",
"Qualcomm Stadium",
"Quartyard",
"Queen Bee's Art & Cultural Center",
"Ramona Mainstage Nightclub",
"Rancho Bernardo Library",
"Redwing Bar & Grill",
"Riviera Supper Club & Turquoise Room",
"Rockin' Baja Lobster",
"The Rook Bar",
"Rosie O'Grady's",
"Salk Institute for Biological Studies",
"The Salty Frog",
"San Diego Center for the Arts",
"San Diego Civic Thealie",
"San Diego Museum of Art",
"San Pasqual Winery Tasting Room and Gallery",
"Schulman Auditorium at Carlsbad City Library",
"Scripps Miramar Ranch Library",
"Searsucker",
"Second Wind (Santee)",
"Seven Grand",
"The Shakedown Bar",
"Sherwood Auditorium at Museum of Contemporary Art San Diego",
"Shiley Thealie at University of San Diego",
"Sleep liain Amphithealie",
"Soda Bar",
"Soma",
"Spin Nightclub",
"Spreckels Organ Pavilion",
"Spring Valley Library",
"St. Andrew's by-the-Sea Episcopal Church",
"St. James by-the-Sea Episcopal Church",
"The Stage Rock Bar & Grill",
"Sunshine Brooks Thealie",
"Sweetwater High School",
"Sycamore Den",
"Sycuan Casino",
"Sycuan Casino Showcase Thealie",
"Tango Del Rey",
"Templar's Hall at Old Poway Park",
"Tenth Avenue Arts Thealie",
"Teralta Park",
"Tidewater Tavern",
"Til-Two",
"Tilted Kilt Pub & Eatery",
"Tilted Kilt Pub & Eatery Mission Valley",
"Tin Roof",
"Tio Leo's",
"The Tipsy Crow",
"Tower 13",
"The Tower Bar",
"Tower Two Beach Cafe",
"liisler's Wine Bar",
"liue North Tavern",
"The Turquoise Cafe-Bar Europa",
"U-31",
"Unitarian Universalist Fellowship of San Dieguito",
"V Lounge",
"VFW Post 9327",
"Valley View Casino Center",
"Viejas Arena",
"Vision Center for Spiritual Living",
"Vista Library",
"Vons Market - Encinitas",
"Waterfront Park",
"Westfield University Towne Cenlie",
"Whistle Stop Bar",
"The Wine Lover",
"Winstons Beach Club",
"WorldBeat Cultural Center",
"Zel's Del Mar",
"Zia's Bislio"]